# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Essential' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Essential
pod 'RxSwift'
pod 'RxCocoa'

  target 'EssentialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EssentialUITests' do
    # Pods for testing
  end

end
